server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: feixiang
    url: jdbc:mysql://127.0.0.1:3307/books?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
wx:
#  我的app信息
#  appId: wx77b0a3692165f501
#  appSecret: 87df80c182ebb5ff81950424b3356448
#  token: mytoken
#  测试app信息
  appId: wxffdeca2f994a2f33
  appSecret: 54c128a7dc39412fd148d7fdec503d1d
  token: mytoken
  redirectUrl: http://sgva8d.natappfree.cc/wx/loginCallback