server:
  port: 8184
## Dubbo:provider
spring:
  dubbo:
    application:
      name: myprovider
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      #-1 从20880开始,自动生成端口
      port: -1
      name: dubbo
    #扫描@com.alibaba.dubbo.config.annotation.Service所在的包
    scan: com.hhf.dubbo.annotation.service