spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/books?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: root
    password: feixiang
  profiles:
    # 一个应用模拟provider和consumer，先启动provider、调用consumer的应用
    active: stream-rabbitmq-provider