server:
  port: 8801

spring:
  application:
    name: cloud-stream-rabbitmq-provider
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitmq的服务信息；
        rabbit1: # 表示定义的名称，用于binding整合,可配置多个。
          type: rabbit # 消息组件类型
          environment: # 设置rabbitmq的相关的环境配置
            spring:
              rabbitmq:
                host: 127.0.0.1
                port: 5672
                username: guest
                password: guest
      bindings: # 服务的整合处理
        my_message_out: # 这个名字是一个通道的名称
          destination: studyExchange # 表示通道my_message_out要使用的Exchange名称为studyExchange
          content-type: application/json # 设置消息类型，文本则设置“text/plain”
          binder: rabbit1 # 设置要绑定的消息服务的具体设置
        my_message_input: # 这个名字是一个通道的名称,对应代码中的名称。以下的配置就是针对这个通道配置的
          destination: studyExchange # 此通道my_message_input要使用名字是studyExchange的Exchange
          content-type: application/json # 设置消息类型，文本则设置“text/plain”
          binder: rabbit1 # 设置要绑定的消息服务的具体设置
          group: myConsumerGroup
      rabbit:
        bindings:
          my_message_out:
            producer:
              delayed-exchange: true # 表示此通道(my_message_out)发送的消息是个延迟消息
          my_message_input:   #如果消费失败，进入死信队列
            consumer:
              delayed-exchange: true
#              acknowledge-mode: manual  #手动ack
              auto-bind-dlq: true
              republish-to-dlq: true
              max-concurrency: 10
              prefetch: 5