server:
  port: 8181
## Dubbo:provider
spring:
  dubbo:
    application:
      name: myprovider
    registry:
      address: zookeeper://127.0.0.1:2181
    protocol:
      port: 20880
      name: dubbo
    #扫描@com.alibaba.dubbo.config.annotation.Service所在的包
    scan: com.hhf.dubbo.annotation.service