server:
  port: 8011
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    initial-size: 5
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    password: feixiang
    url: jdbc:oracle:thin:@127.0.0.1:1521/orcl
    username: scott
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8080/xxl-job-admin
    accessToken:
    executor:
      appname: spring-xxl-job
      addresses:
      ip:
      port: 9999  #调度时的端口
      logpath: /data/applogs/xxl-job/jobhandler
      logretentiondays: 30
logging:
  level:
    com:
      hhf:
        oracle:
          mapper: debug